# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: budget_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
